### ISSUE TITLE
Add rules

### ISSUE THREAD

**Issue by jeddy3** [stylelint/stylelint-config-wordpress#1]
@ntwb Sorry, I've only just seen [your comment](https://github.com/stylelint/stylelint/issues/15#issuecomment-119758993) about setting up this repo. I totally missed it when the issue was closed and we were celebrating the first release of the linter!

Better late than never though :)

I've added some basic tests to make sure the config isn't malformed. I've given you access to the repo though, so you can change anything to your liking :)

Please don't hesitate to give me a shout if you need a hand with anything. And sorry again for the delay!

**Comment by ntwb** [comment]
Awesome, thanks, I'll take a look around and we'll start to get things moving :+1:

**Comment by jeddy3** [comment]
@ntwb I wanted to test out the options validator we've just added to stylelint, so I took a quick stab a round-one of the config.

I'm thinking of releasing `0.1.0` now we have a config. Does that sound good to you?

( p.s. the options validator caught a typo in the config, which was nice :) )

**Comment by ntwb** [comment]
Yes, please do, I'll go create a patch for WordPress and get some more eyes on it.

On 31 Jul 2015, at 7:48 pm, Richard Hallows <notifications@github.com<mailto:notifications@github.com>> wrote:


@ntwb<https://github.com/ntwb> I wanted to test out the options validator we've just added to stylelint, so I took a quick stab a round-one of the config.

I'm thinking of releasing 0.1.0 now we have a config. Does that sound good to you?

( p.s. the options validator caught a typo in the config, which was nice :) )

-

**Comment by ntwb** [comment]
I've added a couple of patches and comments https://core.trac.wordpress.org/ticket/29792#comment:34

Just need to dig around and iterate on our defined rules and/or standards to bring both in sync

**Comment by jeddy3** [comment]
I've just released `0.1.0` for you :)

> I've added a couple of patches and comments https://core.trac.wordpress.org/ticket/29792#comment:34

It's great to see the linter tried against such a large css codebase!

Feel free to give me a shout if you have any questions. I'm going to close this issue now. You have write access to this repo, so feel free to clone and make PRs. Likewise, if you have a npm user I can give you access to publish new versions yourself.

> Just need to dig around and iterate on our defined rules and/or standards to bring both in sync

Good stuff. If you're looking for inspiration on refining your standards then I recommend checking out , if you haven't already, the very sensible [SUITCSS HTML/CSS code style](https://github.com/suitcss/suit/blob/master/doc/STYLE.md). It's a slightly stricter (read: better for a linter) version of the popular [idiomatic CSS](https://github.com/necolas/idiomatic-css) i.e. it's explicit about things like double quotes and alphabetically order properties, whereas the idiomatic one is a bit more ambiguous. The SUITCSS also aligns nicely with the Wordpress one, with a couple of extra holes plugged in.

**Comment by ntwb** [comment]
> I've just released 0.1.0 for you :)

Awesome, thanks very much

> Likewise, if you have a npm user I can give you access to publish new versions yourself.

My NPM username is `netweb` https://www.npmjs.com/~netweb 
(I'm `netweb` at most places on the interwebz :smirk: )

Will also check out the other resources you've linked to help plug any holes we have in our current standards :+1:

**Comment by jeddy3** [comment]
I've added you to npm. Feel free to make releases :) I'm not sure if you'll find it useful, but we've been using https://github.com/MoOx/setup/blob/master/bin/npmrelease to help out with releases. Just change the package.json version number and "Head" bit of the changelog, then run the script for a nice github release :)

Just a thought... tackling those 4000 issues doesn't sound like much fun. Have you thought about running the codebase one-time through csscomb (https://github.com/csscomb/csscomb.js) and postcss-remove-prefixes (https://github.com/johnotander/postcss-remove-prefixes). That'd hopefully address most of issues. Once the codebase is clean, you can then move to stylelint to enforce your styleguide going forward.

> From the original Trac ticket: There may also be a thing or two that we could enforce per our own standards, such as requiring a comment to follow any declaration with !important.

Also, if you're feeling up to it, you can plugin your own rule to support this. Although, that's probably for much later down the line :)

**Comment by MoOx** [comment]
https://github.com/MoOx/setup/blob/master/bin/npmpublish + https://github.com/MoOx/setup/blob/master/bin/npmrelease ;)

**Comment by ntwb** [comment]
Thanks, and I think you meant this https://github.com/MoOx/setup/blob/master/functions/npmpublish plus https://github.com/MoOx/setup/blob/master/bin/npmrelease :smirk: 

I'll definitely take a look at these when it comes time to package up and release a new version and as I've never done said task before I'll take a closer read then, but again much everything you've all done, it is greatly appreciated :smile: 

I'll take a look at those ~4000 issues later next week and whittle down that list significantly, one thing we don't do is [code refactoring should not be done just because we can](https://make.wordpress.org/core/2011/03/23/code-refactoring/), we did pretty well when we previously looked at using CSSLint for all this, I think we can get to a decent place without to much work, but I'll know for better or worse next week ;)

**Comment by jeddy3** [comment]
> I'll take a look at those ~4000 issues later next week and whittle down that list significantly, one thing we don't do is code refactoring should not be done just because we can, 

Makes a lot of sense :)
